# this is for development only.
#
# Use examples directory for normal compose.

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432