---
table: shop
title: Order Pizza
description: |
  Welcome {{.User}}!
  
  Order HOT pizza RIGHT NOW and get
  **huge** discount!
  
  ![](/assets/img/semweb.svg)
  
  _T&C_ can be applied
fields:
  - name: delivery_date
    label: When to deliver
    default: '{{now | date "2006-01-02T15:04"}}'
    required: true
    type: date-time
    icon: "mdi mdi-calendar-range"

  - name: birthday
    label: Your birthday
    default: '{{now | date "2006-01-02"}}'
    description: We will give you a discount
    type: date
    icon: "mdi mdi-cake"

  - name: client_id
    label: Customer
    default: '{{.User}}' # from OIDC
    required: true
    disabled: true
    icon: "mdi mdi-account"

  - name: dough
    label: Dough kind
    default: "thin"
    icon: "mdi mdi-bread-slice"
    options:
      - label: Hand made
        value: hand-made
      - label: Thin crust
        value: thin

  - name: cheese
    label: Pick cheese
    required: true
    multiple: true
    icon: mdi mdi-cheese
    options:
      - label: Italian Mozzarella
        value: mozzarella
      - label: Spanish Cheddar
        value: cheddar
      - label: Something Else
        value: something

  - name: phone
    label: Phone number
    required: true
    icon: mdi mdi-phone-dial
    description: Please use real phone number - we will contact you

  - name: email
    label: EMail
    pattern: '[^@]+@[^@]+'
    default: "{{.Email}}" # from OIDC
    required: true
    icon: mdi mdi-email

  - name: notify_sms
    label: Notify by SMS
    type: boolean
    icon: mdi mdi-message-alert

  - name: zip
    label: ZIP code
    required: true
    type: integer

  - name: address
    label: Full address
    required: true
    multiline: true
    icon: mdi mdi-map-marker

success: |
  ## Thank you!
  
  Your order {{or .Result.ID .Result.id}} is on the way

failed: |
  ## Sorry!
  
  Something went wrong. Please contact our support and tell them the following message:
  
  ```
  {{.Error}}
  ```

webhooks:
  - url: https://example.com/new-pizza
    name: order
    retry: 3
    interval: 10s
    timeout: 30s
    method: PUT
    headers:
      Authorization: token xyz

  - url: https://example.com/notify-to-telegram
    message: |
      #{{ .Result.id }} New pizza ordered.

amqp:
  - key: "form.shop.submission"

  - key: "form.shop.withtype"
    exchange: amq.topic
    type: application/json

  - exchange: amq.topic
    key: "form.shop.{{.Result.id}}"
    retry: 3
    interval: 10s
    timeout: 30s
    headers:
      source: pizza-shop
    id: "{{.Result.id}}"
    correlation: "corr-{{.Result.id}}"
    message: |
      #{{ .Result.id }} New pizza ordered.
