---
title: Simple example
table: simple
fields:
  - name: name
    required: true
  - name: year
    required: true
  - name: comment
    multiline: true
---
# multi documents YAML also supported but requires explicit name
name: birthdays
table: birthday
# (OIDC only) allow only for groups admin OR for users with email domains example.com
policy: '"admin" in groups || email.endsWith("@example.com")'
description: |
  Collect employees birthdays
fields:
  - name: employee
    label: Your name
    required: true
  - name: birthday
    label: Birthday
    type: date
    required: true
---
name: code-access
table: simple
description: Code-based access
fields:
  - name: name
    required: true
    default: "{{.Code}}"
  - name: year
    required: true
    default: '{{.Query.Get "year"}}'
  - name: comment
    multiline: true
codes:
  - reddec