---
title: Simple example
table: simple
fields:
  - name: name
    required: true
  - name: year
    required: true
  - name: comment
    multiline: true
---
# multi documents YAML also supported but requires explicit name
name: birthdays
table: birthday
description: |
  Collect employees birthdays
fields:
  - name: employee
    label: Your name
    required: true
  - name: birthday
    label: Birthday
    type: date
    required: true